
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/users/sv226/everything/clinicalnotes_shift/bashfiles/../pythonscripts/all_attacks_script.py", line 4, in <module>
    from attack_tools import *
  File "/home/users/sv226/everything/clinicalnotes_shift/pythontools/attack_tools.py", line 1, in <module>
    import pandas as pd
  File "/home/users/sv226/.local/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/users/sv226/.local/lib/python3.10/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/users/sv226/.local/lib/python3.10/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/users/sv226/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/users/sv226/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/home/users/sv226/.local/lib/python3.10/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/home/users/sv226/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/home/users/sv226/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/home/users/sv226/.local/lib/python3.10/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/home/users/sv226/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
AttributeError: _ARRAY_API not found
2025-03-31 08:31:52.647975: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-31 08:31:52.662794: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1743424312.680650 2941724 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1743424312.686045 2941724 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1743424312.700512 2941724 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1743424312.700540 2941724 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1743424312.700545 2941724 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1743424312.700553 2941724 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-03-31 08:31:52.704668: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/users/sv226/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
/home/users/sv226/everything/clinicalnotes_shift/pythontools/featurization_tools.py:120: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.sae.load_state_dict(torch.load(path))
/home/users/sv226/everything/clinicalnotes_shift/pythontools/featurization_tools.py:127: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  batch_embeddings = torch.tensor(embeddings[i:i+self.batch_size_sae]).to('cuda')
Traceback (most recent call last):
  File "/home/users/sv226/everything/clinicalnotes_shift/bashfiles/../pythonscripts/all_attacks_script.py", line 114, in <module>
    main()
  File "/home/users/sv226/everything/clinicalnotes_shift/bashfiles/../pythonscripts/all_attacks_script.py", line 102, in main
    mu, ma, l = perform_experiments(experiment, N_trials = N_experiments_per_combo)
  File "/home/users/sv226/everything/clinicalnotes_shift/bashfiles/../pythonscripts/all_attacks_script.py", line 88, in perform_experiments
    m1, m2, l1, l2 = perform_experiment(experiment, test_attacked = test_attacked)
  File "/home/users/sv226/everything/clinicalnotes_shift/bashfiles/../pythonscripts/all_attacks_script.py", line 67, in perform_experiment
    metric1 = experiment.get_note_metric(train_feats, test_feats)
  File "/home/users/sv226/everything/clinicalnotes_shift/experimenttools/attack_experiment_tools.py", line 67, in get_note_metric
    return np.array([nm.dist_feats(train, test) for nm in self.note_metrics])
  File "/home/users/sv226/everything/clinicalnotes_shift/experimenttools/attack_experiment_tools.py", line 67, in <listcomp>
    return np.array([nm.dist_feats(train, test) for nm in self.note_metrics])
  File "/home/users/sv226/everything/clinicalnotes_shift/pythontools/note_metric_tools.py", line 44, in dist_feats
    dist = self.dist_feats_calc(feat1, feat2)
  File "/home/users/sv226/everything/clinicalnotes_shift/pythontools/note_metric_tools.py", line 78, in dist_feats_calc
    feat1 = self.sae.transform(torch.tensor(feat1, dtype = torch.float32)).numpy()
AttributeError: 'numpy.ndarray' object has no attribute 'numpy'. Did you mean: 'dump'?
